version: '4.7.0'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:5000
    volumes:
     - .:/app
    depends_on:
      - db  


  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: donfiles.online
      MYSQL_ROOT_PASSWORD: donfiles.online
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
     - 33067:3306         